"""
Normalised description items for field mapping.

The mapper uses this list to normalise raw description values by
matching them to the closest item via LLM similarity. If the match
confidence is below DESCRIPTION_MATCH_THRESHOLD, the original
description is kept as-is.

The original description is always preserved in the
"orig_description" column for reference.
"""

DESCRIPTION_MATCH_THRESHOLD: float = 0.75

DESCRIPTION_ITEMS: list[str] = [
    "13T Tip Truck - DAY",
    "13T Tip Truck - HOUR",
    "13T Tip Truck - MONTH",
    "13T Tip Truck - WEEK",
    "375cfm Air Compressor (surface) - DAY",
    "375cfm Air Compressor (surface) - HOUR",
    "375cfm Air Compressor (surface) - MONTH",
    "375cfm Air Compressor (surface) - WEEK",
    "375cfm Air Compressor (underground) - DAY",
    "375cfm Air Compressor (underground) - HOUR",
    "375cfm Air Compressor (underground) - MONTH",
    "375cfm Air Compressor (underground) - WEEK",
    "5T Excavator - DAY",
    "5T Excavator - HOUR",
    "5T Excavator - MONTH",
    "5T Excavator - WEEK",
    "Abrasive Blast & Paint (skid mounted surface kit) inc. 375cfm compressor - DAY",
    "Abrasive Blast & Paint (skid mounted surface kit) inc. 375cfm compressor - HOUR",
    "Abrasive Blast & Paint (skid mounted surface kit) inc. 375cfm compressor - MONTH",
    "Abrasive Blast & Paint (skid mounted surface kit) inc. 375cfm compressor - WEEK",
    "Abrasive Blast & Paint (skid mounted underground kit) inc. 375cfm compressor - DAY",
    "Abrasive Blast & Paint (skid mounted underground kit) inc. 375cfm compressor - HOUR",
    "Abrasive Blast & Paint (skid mounted underground kit) inc. 375cfm compressor - MONTH",
    "Abrasive Blast & Paint (skid mounted underground kit) inc. 375cfm compressor - WEEK",
    "Abrasive blast unit - DAY",
    "Abrasive blast unit - HOUR",
    "Abrasive blast unit - MONTH",
    "Abrasive blast unit - WEEK",
    "Abrasive unit, truck mounted - DAY",
    "Abrasive unit, truck mounted - HOUR",
    "Abrasive unit, truck mounted - MONTH",
    "Abrasive unit, truck mounted - WEEK",
    "Bobcat (wheeled) Surface - DAY",
    "Bobcat (wheeled) Surface - HOUR",
    "Bobcat (wheeled) Surface - MONTH",
    "Bobcat (wheeled) Surface - WEEK",
    "Bobcat (wheeled) UG - DAY",
    "Bobcat (wheeled) UG - HOUR",
    "Bobcat (wheeled) UG - MONTH",
    "Bobcat (wheeled) UG - WEEK",
    "Boilermaker - DS",
    "Boilermaker - NS",
    "Coded Welder / Qualified Pipe Welder - DS",
    "Coded Welder / Qualified Pipe Welder - NS",
    "Compressor 175 cfm - DAY",
    "Compressor 175 cfm - HOUR",
    "Compressor 175 cfm - MONTH",
    "Compressor 175 cfm - WEEK",
    "Concrete Pump, UG - DAY",
    "Concrete Pump, UG - HOUR",
    "Concrete Pump, UG - MONTH",
    "Concrete Pump, UG - WEEK",
    "Concreter - DS",
    "Concreter - NS",
    "Crane 15T Franna, UG - DAY",
    "Crane 15T Franna, UG - HOUR",
    "Crane 15T Franna, UG - MONTH",
    "Crane 15T Franna, UG - WEEK",
    "Crane 20T Franna Surface - DAY",
    "Crane 20T Franna Surface - HOUR",
    "Crane 20T Franna Surface - MONTH",
    "Crane 20T Franna Surface - WEEK",
    "Crane 20T Franna, UG - DAY",
    "Crane 20T Franna, UG - HOUR",
    "Crane 20T Franna, UG - MONTH",
    "Crane 20T Franna, UG - WEEK",
    "Crane Operator - DS",
    "Crane Operator - NS",
    "Electrical LH - DS",
    "Electrical LH - NS",
    "Electrical Supervisor - DS",
    "Electrical Supervisor - NS",
    "Electrician - DS",
    "Electrician - NS",
    "Fitter - DS",
    "Fitter - NS",
    "HSE Advisor - DS",
    "HSE Advisor - NS",
    "Instrument Tech - DS",
    "Instrument Tech - NS",
    "IT Loader, UG - DAY",
    "IT Loader, UG - HOUR",
    "IT Loader, UG - MONTH",
    "IT Loader, UG - WEEK",
    "Labourer - DS",
    "Labourer - NS",
    "Mechanic / Special Class Fitter - DS",
    "Mechanic / Special Class Fitter - NS",
    "Mechanical LH - DS",
    "Mechanical LH - NS",
    "Mechanical Supervisor - DS",
    "Mechanical Supervisor - NS",
    "Operator - DS",
    "Operator - NS",
    "Painter / Blaster - DS",
    "Painter / Blaster - NS",
    "Poly Welder - DAY",
    "Poly Welder - HOUR",
    "Poly Welder - MONTH",
    "Poly Welder - WEEK",
    "Pressure Cleaner - DAY",
    "Pressure Cleaner - HOUR",
    "Pressure Cleaner - MONTH",
    "Pressure Cleaner - WEEK",
    "Project Engineer - DS",
    "Project Engineer - NS",
    "Project Manager - DS",
    "Project Manager - NS",
    "Rail Civil Labourer / Operator - DS",
    "Rail Civil Labourer / Operator - NS",
    "Rail Civil Tradesperson - DS",
    "Rail Civil Tradesperson - NS",
    "Rail Maintenance SME - DS",
    "Rail Maintenance SME - NS",
    "Rail Maintenance Supervisor - DS",
    "Rail Maintenance Supervisor - NS",
    "Rail Maintenance Technical Specialist Level 1 - DS",
    "Rail Maintenance Technical Specialist Level 1 - NS",
    "Rail Maintenance Technical Specialist Level 2 - DS",
    "Rail Maintenance Technical Specialist Level 2 - NS",
    "Rigger (Advanced) - DS",
    "Rigger (Advanced) - NS",
    "Rigger (Intermediate) - DS",
    "Rigger (Intermediate) - NS",
    "Rope Access Level 2 - DS",
    "Rope Access Level 2 - NS",
    "Rope Access Level 3 - DS",
    "Rope Access Level 3 - NS",
    "Senior Project Engineer - DS",
    "Senior Project Engineer - NS",
    "Sentry - DS",
    "Sentry - NS",
    "Sheetmetal Worker - DS",
    "Sheetmetal Worker - NS",
    "Slew Crane 55T - DAY",
    "Slew Crane 55T - HOUR",
    "Slew Crane 55T - MONTH",
    "Slew Crane 55T - WEEK",
    "Spray Unit - DAY",
    "Spray Unit - HOUR",
    "Spray Unit - MONTH",
    "Spray Unit - WEEK",
    "Superintendent - DS",
    "Superintendent - NS",
    "Supervisor - DS",
    "Supervisor - NS",
    "Surface 2x4 Ute - DAY",
    "Surface 2x4 Ute - HOUR",
    "Surface 2x4 Ute - MONTH",
    "Surface 2x4 Ute - WEEK",
    "Surface 4x4 Ute - DAY",
    "Surface 4x4 Ute - HOUR",
    "Surface 4x4 Ute - MONTH",
    "Surface 4x4 Ute - WEEK",
    "Trades Assistant / Labourer - DS",
    "Trades Assistant / Labourer - NS",
    "Tradesman Trailer (civils kit) - DAY",
    "Tradesman Trailer (civils kit) - HOUR",
    "Tradesman Trailer (civils kit) - MONTH",
    "Tradesman Trailer (civils kit) - WEEK",
    "Trowelling machine - DAY",
    "Trowelling machine - HOUR",
    "Trowelling machine - MONTH",
    "Trowelling machine - WEEK",
    "Truck 12T, UG - DAY",
    "Truck 12T, UG - HOUR",
    "Truck 12T, UG - MONTH",
    "Truck 12T, UG - WEEK",
    "Truck 4T Flat Bed Surface - DAY",
    "Truck 4T Flat Bed Surface - HOUR",
    "Truck 4T Flat Bed Surface - MONTH",
    "Truck 4T Flat Bed Surface - WEEK",
    "Truck 8T Flat Bed Single Cab UG - DAY",
    "Truck 8T Flat Bed Single Cab UG - HOUR",
    "Truck 8T Flat Bed Single Cab UG - MONTH",
    "Truck 8T Flat Bed Single Cab UG - WEEK",
    "Truck 8T Surface - DAY",
    "Truck 8T Surface - HOUR",
    "Truck 8T Surface - MONTH",
    "Truck 8T Surface - WEEK",
    "Truck 9T Flat Bed Single Cab Surface - DAY",
    "Truck 9T Flat Bed Single Cab Surface - HOUR",
    "Truck 9T Flat Bed Single Cab Surface - MONTH",
    "Truck 9T Flat Bed Single Cab Surface - WEEK",
    "Underground 4x4 - DAY",
    "Underground 4x4 - HOUR",
    "Underground 4x4 - MONTH",
    "Underground 4x4 - WEEK",
    "Water Cart - DAY",
    "Water Cart - HOUR",
    "Water Cart - MONTH",
    "Water Cart - WEEK",
    "Welder 400 Amp - DAY",
    "Welder 400 Amp - HOUR",
    "Welder 400 Amp - MONTH",
    "Welder 400 Amp - WEEK",
    "Welder 400 Amp Welder trailer mount - DAY",
    "Welder 400 Amp Welder trailer mount - HOUR",
    "Welder 400 Amp Welder trailer mount - MONTH",
    "Welder 400 Amp Welder trailer mount - WEEK",
    "Welder Vantage 575 UG - DAY",
    "Welder Vantage 575 UG - HOUR",
    "Welder Vantage 575 UG - MONTH",
    "Welder Vantage 575 UG - WEEK",
]

# DESCRIPTION_ITEMS: list[str] = [
#     "AN, including any Moranbah Additional Volumes",
#     "Titan 2000 (Standard Emulsion)",
#     "Titan 5000 (Specialty Emulsion)",
#     "Titan 9000 (Specialty Emulsion)",
#     "N-2 (Specialty Emulsion bulk additive)",
#     "AN reprocessing fee",
#     "Bajool AN handling fee",
#     "DSPLUS 4G V2 BIP 60FT/18M 52/CS",
#     "DSPLUS 4G V2 BIP 80FT/24M 40/CS",
#     "DSPLUS 4G V2 BIP 100FT/30M 32CS",
#     "DSPLUS 4G V2 BIP 120FT/37M 24/CS",
#     "DSPLUS 4G V2 BIP 150FT/46M 20/CS",
#     "DSPLUS 4G V2 BIP 180FT/55M 16/CS",
#     "DSPLUS 4G V2 BIP 214FT/65M 16/CS",
#     "DSPLUS 4G V2 BIP 245FT/75M 16/CS",
#     "SURFACE WIRE, 0.60MM, CU 500M 2/C",
#     "Surface Wire, 0.60MM, CU 1000FT 2/CS",
#     "Gel Clips (100 pack)",
#     "DIGISHOT PLUS HARNESS WIRE CONNECTOR",
#     "CRIMP TOOL",
#     "FIBB Block DIGISHOT (100 pack)",
#     "Nonel MS 6.0 m",
#     "Nonel MS 7.2 m",
#     "Nonel MS 9.0 m",
#     "Nonel MS 12.0 m",
#     "Nonel MS 15.0 m",
#     "Nonel MS 18.0 m",
#     "Nonel MS HD 7.2",
#     "Nonel MS HD 9.0",
#     "Nonel MS HD 12.0 m",
#     "Nonel MS HD 15.0 m",
#     "Nonel MS HD 18.0 m",
#     "Nonel MS HD 24.0 m",
#     "Nonel MS HD 30.0 m",
#     "Nonel MS HD 36.0 m",
#     "Nonel MS HD 45.0 m",
#     "Nonel MS HD 60.0 m",
#     "Nonel MS HD 80.0 m",
#     "Nonel EZTL 15.0m",
#     "MS Connectors",
#     "Primacord 5-A 5.3 G/M (25GR/FT) 1000M/C",
#     "PRIMALINE 10-A 10.6 G/M (50GR/FT)",
#     "NONEL PRIMAFIRE 700MM #0 0MS",
#     "NONEL STARTER 100M",
#     "NONEL STARTER 500M",
#     "NONEL LEAD LINE 1000M",
#     "TROJAN NB UNIVERSAL 400G 20/CS",
#     "TROJAN SPARTAN 150G EXPORT 48/CS",
#     "TROJAN SPARTAN 400G AUSTRALIA 20/CS",
#     "Solarcast-P 400G PShell 5 24/CS",
#     "Booster freight",
#     "NONEL STARTER GUN DNE HN1",
#     "DYNOSTART DS2",
#     "ELECTRODE FOR DYNOSTART",
#     "SHOTShell PRIMERS",
#     "PRIMER CAPS HN1",
#     "DETONATING CORD CUTTERS",
#     "J STYLE CORD CUTTERS",
#     "NONEL JOINER KIT LARGE (I EA = 1 BAG)",
#     "Commander",
#     "CE4 Tagger V3",
#     "12 hour Day Shift (MPU Only) Wet Hire rate",
#     "12 hour Night Shift (MPU Only) Wet Hire rate)",
#     "12.5 hour Day Shift (MPU Only) Wet Hire rate",
#     "12.5 hour Night Shift (MPU Only) Wet Hire rate)",
#     "12 hour Day Shift MPU Operator/ Yard Hand",
#     "12 hour Night Shift MPU Operator/ Yard Hand",
#     "12 hour Day Shift (MPU Only) Wet Hire",
#     "12 hour Night Shift (MPU Only) Wet Hire",
#     "12.5 hour Day Shift (MPU Only) Wet Hire rate",
#     "12.5 hour Night Shift (MPU Only) Wet Hire rate)",
#     "12 hour Day Shift (TTT MPU Only)",
#     "12 hour Night Shift (TTT MPU Only)",
#     "12.5 hour Day Shift (TTT MPU Only)",
#     "12.5hour Night Shift (TTT MPU Only)",
#     "12 hour Day Shift MPU Operator",
#     "12 hour Night Shift MPU Operator",
#     "12.5hour Day Shift MPU Operator",
#     "12.5hour Night Shift MPU Operator",
#     "Technical Support Fee",
#     "Blast Design Engineer",
#     "Dyno Consult engineering support",
#     "Gassing Technology",
#     "Tube-veyor (auger)",
#     "Fuel Cell",
#     "Gassing Reload",
#     "Scales & Bins",
#     "Tipping Frame",
#     "EP Storage Tank",
#     "Light Vehicle",
#     "Storage Container",
#     "MPU Decontamination",
#     "Night Shift Lights",
#     "De-Mobilisation",
#     "MPU Fitters",
#     "Back to Back Area Supervisors",
#     "Trainer",
#     "Admin",
#     "Relief Operators",
#     "Parts Manager",
#     "Offsite BMA MPU maintenance facility & office",
#     "Back to Back Area Maintenance Supervisors",
#     "Gassing Chemicals",
#     "Floater Trucks",
#     "HSE",
#     "Area Manager",
#     "Undiscounted Total Operating Fee $/Month",
#     "Caval Ridge",
#     "Goonyella",
#     "Peak Downs",
#     "Saraji",
# ]
